server:
  port: 9191
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/employees/**
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/departments/**
        - id: ORGANIZATION-SERVICE
          uri: lb://ORGANIZATION-SERVICE
          predicates:
            - Path=/api/organizations/**

  sleuth:
    sampler:
      probability: 1.0
