spring:
  application:
    name: ORGANIZATION-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0
  jackson:
    serialization:
      indent-output: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
#busrefresh

#  datasource:
#    url: jdbc:mysql://localhost:3306/organization_db
#    username: root
#    password: 1003
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#server:
#  port: 8083
#eureka:
#  instance:
#    client:
#      serverUrl:
#        defaultZone: http://localhost:8761/eureka/
